#let denotation-entries = (
  ([PI], [Polyimide]),
  ([MPI], [Polyimide model compound, N-phenylphthalimide]),
  ([PBI], [Polybenzimidazole]),
  ([MPBI], [Polybenzimidazole model compound, N-phenylbenzimidazole]),
  ([PY], [Polypyrrolone]),
  ([PMDA-BDA], [Polypyrrolone film synthesized from PMDA and BDA]),
  ([MPY], [Polypyrrolone model compound]),
  ([As-PPT], [Asymmetric polyphenyl triazine]),
  (
    [MAsPPT],
    [Asymmetric polyphenyl triazine monomer model compound,
      3,5,6-triphenyl-1,2,4-triazine],
  ),
  (
    [DMAsPPT],
    [Asymmetric polyphenyl triazine dimer model compound used in hydrolysis
      experiments],
  ),
  ([S-PPT], [Symmetric polyphenyl triazine]),
  (
    [MSPPT],
    [Symmetric polyphenyl triazine model compound,
      2,4,6-triphenyl-1,3,5-triazine],
  ),
  ([PPQ], [Polyphenylquinoxaline]),
  ([MPPQ], [Polyphenylquinoxaline model compound, 3,4-diphenylbenzo-2-diazine]),
  ([HMPI], [Protonated product of the polyimide model compound]),
  ([HMPY], [Protonated product of the polypyrrolone model compound]),
  ([HMPBI], [Protonated product of the polybenzimidazole model compound]),
  (
    [HMAsPPT],
    [Protonated product of the asymmetric polyphenyl triazine model compound],
  ),
  (
    [HMSPPT],
    [Protonated product of the symmetric polyphenyl triazine model compound],
  ),
  ([HMPPQ], [Protonated product of the polyphenylquinoxaline model compound]),
  ([PDT], [Thermal decomposition temperature]),
  ([HPLC], [High-performance liquid chromatography]),
  ([HPCE], [High-performance capillary electrophoresis]),
  ([LC-MS], [Liquid chromatography–mass spectrometry]),
  ([TIC], [Total ion content]),
  ([#emph[ab initio]], [First-principles quantum-chemistry calculation method]),
  ([DFT], [Density functional theory]),
  ($E_a$, [Activation energy of a chemical reaction]),
  ([ZPE], [Zero-point vibrational energy]),
  ([PES], [Potential energy surface]),
  ([TS], [Transition state]),
  ([TST], [Transition-state theory]),
  ($Delta G^(dagger.double)$, [Activation free energy]),
  ($kappa$, [Transmission coefficient]),
  ([IRC], [Intrinsic reaction coordinate]),
  ($nu_i$, [Imaginary frequency]),
  (
    [ONIOM],
    [Our Own N-layered Integrated Molecular Orbital and Molecular Mechanics],
  ),
  ([SCF], [Self-consistent field]),
  ([SCRF], [Self-consistent reaction field]),
)
