[package]
name = "tntt"
version = "0.6.0"
entrypoint = "src/lib.typ"
authors = ["chillcicada"]
license = "MIT"
description = "Tntt is Not an official Typst Thesis Template for Tsinghua university (THU)..."
repository = "https://github.com/tuna/thuthesis-typst"
keywords = ["Tsinghua University", "thesis", "template", "THU"]
categories = ["thesis"]
exclude = [".*", "build", "contrib", "scripts", "tests"]
compiler = "0.15.1"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
