[windows]
SongTi = [{ name = "Times New Roman", covers = "latin-in-cjk" }, "NSimSun"]
HeiTi = [{ name = "Arial", covers = "latin-in-cjk" }, "SimHei"]
KaiTi = [{ name = "Arial", covers = "latin-in-cjk" }, "SimKai"]
FangSong = [{ name = "Times New Roman", covers = "latin-in-cjk" }, "FangSong"]
Mono = [{ name = "Courier New", covers = "latin-in-cjk" }, "FangSong"]
Math = ["New Computer Modern Math", "KaiTi"]

[macos]
SongTi = [{ name = "Times New Roman", covers = "latin-in-cjk" }, "STSong", "Songti SC"]
HeiTi = [{ name = "Arial", covers = "latin-in-cjk" }, "STHeiti", "Heiti SC"]
KaiTi = [{ name = "Arial", covers = "latin-in-cjk" }, "STKaiti", "Kaiti SC"]
FangSong = [{ name = "Times New Roman", covers = "latin-in-cjk" }, "STFangsong", "FangSong SC"]
Mono = [{ name = "Courier New", covers = "latin-in-cjk" }, "STFangsong", "FangSong SC"]
Math = ["New Computer Modern Math", "STKaiti", "Kaiti SC"]

[fandol]
SongTi = [{ name = "TeX Gyre Termes", covers = "latin-in-cjk" }, "FandolSong"]
HeiTi = [{ name = "TeX Gyre Heros", covers = "latin-in-cjk" }, "FandolHei"]
KaiTi = [{ name = "TeX Gyre Heros", covers = "latin-in-cjk" }, "FandolKai"]
FangSong = [{ name = "TeX Gyre Termes", covers = "latin-in-cjk" }, "FandolFang R"]
Mono = [{ name = "TeX Gyre Cursor", covers = "latin-in-cjk" }, "FandolFang R"]
Math = ["XITS Math", "New Computer Modern Math", "FandolKai"]

[ubuntu]
SongTi = [{ name = "TeX Gyre Termes", covers = "latin-in-cjk" }, "Noto Serif CJK SC", "Source Han Serif", "FandolSong"]
HeiTi = [{ name = "TeX Gyre Heros", covers = "latin-in-cjk" }, "Noto Sans CJK SC", "Source Han Sans", "FandolHei"]
KaiTi = [{ name = "TeX Gyre Heros", covers = "latin-in-cjk" }, "FandolKai"]
FangSong = [{ name = "TeX Gyre Termes", covers = "latin-in-cjk" }, "FandolFang R"]
Mono = [{ name = "TeX Gyre Cursor", covers = "latin-in-cjk" }, "FandolFang R"]
Math = ["XITS Math", "New Computer Modern Math", "FandolKai"]
