[zh]
committee = "学位论文指导小组、公开评阅人和答辩委员会名单"
supervisors = "指导小组名单"
reviewers = "公开评阅人名单"
defenders = "答辩委员会名单"
anonymous-review = "无（全隐名评阅）"

outline = "目　录"
figure-table-list = "插图和附表清单"
master-list = "插图和附表清单"
figure-list = "插图清单"
table-list = "附表清单"
equation-list = "公式清单"
notation = "符号和缩略语说明"
bibliography = "参考文献"
acknowledge = "致　谢"
comments = "指导教师学术评语"
resolution = "答辩委员会决议书"

error-lang = "不支持的语言："
error-degree = "不支持的学位："
error-degree-type = "不支持的学位类型："

[en]
committee = "THESIS SUPERVISION COMMITTEE, REVIEWERS, AND DEFENSE COMMITTEE"
supervisors = "Thesis Supervision Committee"
reviewers = "External Reviewers"
defenders = "Defense Committee"
anonymous-review = "Anonymous review"

outline = "TABLE OF CONTENTS"
figure-table-list = "List of Figures and Tables"
master-list = "List of Figures and Tables"
figure-list = "FIGURES"
table-list = "TABLES"
equation-list = "EQUATIONS"
notation = "ABBREVIATIONS"
bibliography = "REFERENCES"
acknowledge = "ACKNOWLEDGEMENTS"
comments = "COMMENTS FROM THE THESIS SUPERVISOR"
resolution = "RESOLUTION OF THESIS DEFENSE COMMITTEE"

error-lang = "Unsupported language: "
error-degree = "Unsupported degree: "
error-degree-type = "Unsupported degree type: "
