name: Render nightly thesis
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "template/**"
      - "scripts/**"
      - "typst.toml"
      - ".github/workflows/build.yml"
  pull_request:
    types: [opened, edited, synchronize]
    paths:
      - "src/**"
      - "template/**"
      - "scripts/**"
      - "typst.toml"
      - ".github/workflows/build.yml"
  workflow_dispatch:
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Setup Typst
        uses: typst-community/setup-typst@v5
        with:
          typst-version: 0.15.1
      - name: Prepare open fonts
        run: bash scripts/fonts.sh fonts
      - name: Render templates
        run: bash scripts/build.sh
      - name: Upload Artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: thesis
          path: build/nightly/*.pdf
          if-no-files-found: error
